apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lava-duel-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lava-duel-service
            port:
              number: 80
